services:

  postgres:
    container_name: postgres
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=${USER}
      - POSTGRES_PASSWORD=${PASSWORD}
    networks:
      - main
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data_rss:/var/lib/postgresql/data
